README.md, app/api/submission/generate_helpers.rb, app/api/task_definitions.rb, app/api/tasks.rb, app/models/group_submission.rb, app/models/project.rb, app/models/task.rb, app/models/task_definition.rb, app/serializers/task_definition_serializer.rb, app/views/layouts/application.pdf.erbtex, db/migrate/20160223054040_add_ability_for_graded_tasks.rb, db/schema.rb, public/resources/marking_package_readme.txt
Tasks can now be marked as "graded tasks", which means that a task is complete to a specific standard:
> The concept map was completed to a **high distinction** standard.
vs.
> The concept map was completed to a **pass** standard.
Other additions include some minor refactoring to the batch download/upload functionality including a new `readme.txt` that is included to help tutors assess the `marks.csv` file.
=> Add graded task functionality

config/database.yml, config/environments/experimental.rb
Updates made to the experimental environment configuration
files allowing git to work correctly with Ubuntu v14.
=> CONFIG: Add Experimental Environment configuration

Gemfile, Gemfile.lock, config/application.rb, db/seeds.rb, test/models/user_test.rb, test/test_helper.rb
This merge will add support for minitest
=> TEST: Add support for minitest framework

Dockerfile, README.md, app/helpers/file_helper.rb, app/helpers/timeout_helper.rb, app/models/project.rb
Cherry picked commit https://github.com/doubtfire-lms/doubtfire-api/commit/7b9cb00a5e8f35e3c15daa0e54284cba9d55a162 from another branch.
Refer to conversation at https://github.com/doubtfire-lms/doubtfire-api/pull/16
=> Remove PDFtk for aggregating and compressing PDFs

Gemfile, Gemfile.lock
This commit fixes the gemfile so that rake test works
=> FIX: Add minitest-arount back to gemfile

README.md
Mentions 2016 install onward to resolve `shellesc.sty` issue.
=> DOCS: Update LaTeX install in README

config/secrets.yml
=> Add anchors to duplicate dev secrets in test & replica

app/api/units.rb, app/models/task.rb, app/models/task_comment.rb, app/models/unit.rb, app/serializers/task_serializer.rb
Adds endpoint for task inbox. Stubs data as applicable. Added `TODO: JAKE - <msg>` for areas that need real data for @jakerenzella to do as discussed with @macite.
=> Stub new task inbox endpoint

app/api/users.rb, app/models/unit.rb, app/models/user.rb, app/serializers/user_serializer.rb, db/migrate/20170112231900_add_student_id_to_user.rb, db/schema.rb
This PR will add the migration, model validations and support for User.student_id
=> Feature/add student_id to user

app/api/submission/portfolio_evidence_api.rb, app/models/task.rb
Adds the functionality to map ILOs to tasks on the submission upload API
Required for the new student view.
=> Add ILO alignments on submission

app/api/task_comments.rb, app/serializers/task_comment_serializer.rb
Needed for web Gravatar changes
=> Add email address to comments API

app/models/unit.rb, lib/tasks/checks.rake, test_files/link_template.html
To make one link use:
rake submission:simulate_plagiarism
To make multiple, say 10, use:
rake 'submission:simulate_plagiarism[10]'
Will make links only in the first unit.
=> NEW: Add plagiarism link simulator rake task

Gemfile.lock, setup.sh
Fix for `Gemfile.lock` issues #68. Removes `< 5` dependency from `rails-latex` as this was causing installation issues on Sierra. Also updates DSTIL hooks.
=> FIX: Fix installation script for Sierra compatibility

app/helpers/file_helper.rb
Fix issue with PDF file size check
=> FIX: Ensure PDF seek checks file size

.travis.yml, README.md, test/api/units/task_definitions_test.rb
Works for both staging and testing environment
=> Travis CI integration

app/api/task_comments.rb, app/helpers/file_helper.rb, app/models/task.rb, app/models/task_comment.rb
=> NEW: Support for PDF comments in the back end

app/models/unit.rb, test_files/unit_csv_imports/import_group_tasks.csv
To better enable transitions of groups between units.
=> ENHANCE: Add ability to create tutorials on group import

app/models/project.rb, config/deakin.rb
This PR will fix an issue where students would still see units they had withdrawn from in their current units.
=> FIX: Correct issue where withdrawn units were still listed

config/deakin.rb
This PR updates sync scripts for Deakin to allow automatic import of students.
=> FIX: Update sync script for importing students

config/deakin.rb
This PR fixes some issues associated with syncing Deakin students.
=> Correct issue syncing unit enrolments

config/deakin.rb
=> FIX: Correct issue with duplication of cloud tutorials

app/api/campuses_authenticated_api.rb, app/api/campuses_public_api.rb, app/api/projects_api.rb, app/api/tutorials_api.rb, app/api/units_api.rb, app/models/campus.rb, app/models/project.rb, app/models/tutorial.rb, app/models/unit.rb, app/serializers/project_serializer.rb, app/serializers/tutorial_serializer.rb, config/deakin.rb, db/migrate/20191009005448_add_abbreviation_to_campuses.rb, db/schema.rb, lib/helpers/database_populator.rb, lib/tasks/populate.rake, spec/models/project_spec.rb, test/api/campuses_test.rb, test/api/tutorials_test.rb, test/api/units_test.rb, test/factories/campuses_factory.rb, test/factories/units_factory.rb, test/models/campus_test.rb, test/models/project_test.rb
This PR introduces the campus....
=> FEATURE: Add campus [ON-69] [ON-78]

app/api/campuses_authenticated_api.rb, app/models/campus.rb, db/migrate/20191011035719_add_active_to_campuses.rb, db/schema.rb, lib/helpers/database_populator.rb, test/factories/campuses_factory.rb
This PR will add active to campus....
This PR should get merged after #202 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> FEATURE: Add active to campus [ON-79]

app/api/activity_types_authenticated_api.rb, app/api/activity_types_public_api.rb, app/api/api.rb, app/models/activity_type.rb, app/models/user.rb
This PR will add activity type endpoints....
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> FEATURE: Activity Types endpoints [ON-81]

app/models/activity_type.rb, db/migrate/20191024222811_create_activity_types.rb, db/schema.rb, test/factories/activity_types.rb, test/models/activity_type_test.rb
This PR will add activity type to the database....
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> FEATURE: Add activity type [ON-96]

.ci-setup/texlive-install.sh, app/api/units_api.rb, test/api/tutorials_test.rb, test/api/units_test.rb
Fix the current outstanding PR that adds tutorial tests.
=> Add tests for tutorial

test/api/activity_types_api_test.rb, test/api/groups_test.rb, test/api/tasks_test.rb, test/api/tutorials_test.rb
Adjust some existing tests that are using system data to use data generated by FactoryGirl instead to avoid database re-populated; assign correct users to API calls
=> QUALITY: Adjust tests to use factorygirl data instead of existing data

README.md, setup.sh
N.b., this was a previously-submitted pull request with improper commit messages; issues were encountered trying to fix, so it was necessary to redo the commits and the pull request. Also updated git source address for rbenv.
This PR seeks to update the Doubtfire-api installation instructions, documentation, and scripts. The target development environment is Ubuntu 18.04 LTS. Installation instructions as previously prescribed did not work.
The changes have been tested using a fresh installation of Ubuntu 18.04 LTS; first manually, and then using the ./setup.sh script.
=> FIX: Linux installation script and documentation

test/api/activity_types_api_test.rb
Added unit test for test_ delete_activity_type
=> TEST:Add unit test for test delete activity type

app/api/task_definitions_api.rb, app/api/tasks_api.rb, app/models/project.rb, app/models/tutorial_enrolment.rb, app/models/unit.rb, db/migrate/20200210021949_remove_tutorial_enrolment_stream.rb, db/schema.rb, test/api/tasks_test.rb, test/api/units/task_definitions_test.rb, test/factories/tutorial_enrolments_factory.rb, test/factories/users_factory.rb, test/models/tutorial_enrolment_model_test.rb, test/models/unit_model_test.rb
Remove the need for tutorial enrolments to have stream ids - avoid duplication.
=> QUALITY - Remove need for streams in tutorial enrolment

app/models/unit.rb
This adds the campus id to each student within a unit. Needed to do something like this so that on the refactored students view on the front end, I needed a way to check to see if a project's campus matched that of a tutorial that they were to enrol in.
=> NEW: Add campus id to unit students

app/api/task_comments_api.rb, app/api/tutorial_enrolments_api.rb, app/api/tutorial_streams_api.rb, app/models/comments/task_comment.rb, app/models/project.rb, app/models/task.rb, app/models/tutorial_enrolment.rb, app/models/unit.rb, app/serializers/unit_role_serializer.rb, app/serializers/unit_serializer.rb, config/deakin.rb, config/no_institution_setting.rb, db/migrate/20200120043523_add_reply_id_to_task_comments.rb, db/schema.rb, test/api/comments/comment_test.rb, test/api/students_api_test.rb, test/api/tutorial_stream_api_test.rb, test/helpers/json_helper.rb, test/models/tutorial_enrolment_model_test.rb, test/models/unit_model_test.rb
Adds backend support for reply_ids
All tests pass
=> New: Comment replies

app/api/tutorial_enrolments_api.rb, app/models/unit.rb, config/deakin.rb, config/no_institution_setting.rb
Add integration to update streams and tutorials via integrations.
=> Akshat bajaj feature/deakin integration

app/models/unit.rb, config/deakin.rb
Corrects an issue where Deakin students are not correctly added to tutorials based on the timetable.
=> Fix Deakin Tutorial Sync

Gemfile.lock, app/views/layouts/application.pdf.erbtex
Fix issue with update latex rails gem - correct latex config to run two passes and use lualatex.
Local test.
=> Fix portfolio generation

.rubocop_todo.yml
Disable all these arbitrary limits for now until we have enough time to look into these.
=> chore: disable more limits for rubocop

.github/workflows/deployment.yml
Update all GitHub docker-related actions. These changes are just for upkeeping and should not affect the existing CI.
- `docker/build-push-action` to v2 to v3 ([changelog](https://github.com/docker/build-push-action/compare/v2.10.0...v3.2.0))
- `docker/metadata-action` to v3 to v4 ([changelog](https://github.com/docker/metadata-action/compare/v3.8.0...v4.1.1))
- `docker/login-action` to v1 to v2 ([changelog](https://github.com/docker/login-action/compare/v1.14.1...v2.1.0
))
- `docker/setup-buildx-action` from v1 to v2 ([changelog](https://github.com/docker/setup-buildx-action/compare/v1.7.0...v2.2.1))
Ensure the PR CI is completed and green before merging.
=> build: update GitHub docker related actions

.github/workflows/deployment.yml
Update GitHub `actions/checkout` from v2 to v3.
Full changelog https://github.com/actions/checkout/compare/v2.5.0...v3.1.0
Ensure the PR CI is completed and green before merging.
=> build: update GitHub actions/checkout to v3
