config/database.yml
test/api/auth_test.rb
test/helpers/auth_helper.rb
test/test_helper.rb

This sees the inclusion of endpoint testing for `auth` for `post`, `put` and `delete`

TEST: Add test for API end point auth

---

app/api/learning_alignment.rb
app/api/task_definitions.rb
app/api/units.rb
app/api/users.rb
app/models/unit.rb
app/models/user.rb

Whilst trying to download CSV of task statistics as a tutor:
> `{"error":"Not authorised to download CSV of student tasks in COS10009-COS60006"}`
Convenors could only download CSV-related content about a unit. This is separated into a new permission, `:download_unit_csv`, for all content that can be downloaded about a unit (including download task statistics).
Administation content, such as downloading a list of all user is now separated into `:download_system_csv`, which is restricted to administrator system roles only.

Fix CSV download for task statistics

---

Gemfile
Gemfile.lock
lib/helpers/database_populator.rb
lib/helpers/randomizer.rb
lib/tasks/test_setup.rake
test/api/auth_test.rb
test/api/units_test.rb
test/helpers/auth_helper.rb
test/helpers/json_helper.rb
test/test_helper.rb

@jakerenzella and myself worked on fixing the test framework to ensure all tests use minitest and that transactions are used on our [new/helpdesk-ticketing](https://github.com/final-year-project/doubtfire-api/tree/new/helpdesk-ticketing) branch. This pull request cherry-picks those commits into this branch so that it can be implemented in [develop](https://github.com/doubtfire-api/doubtfire-api/tree/develop)

Fix minitest framework and add additional helpers

---

Gemfile.lock
app/api/authentication.rb
app/helpers/authentication_helpers.rb
app/models/user.rb

Prevents users from seeing a API JSON response after they have authenticated via AAF.
```
[WEB]          [API]             [AFF]
|------------------------------->|         (1)
|<----------------|         (2)
|<-------------|                           (3)
|------------->|                           (4)
|<-------------|                           (5)
```
Where:
1) ask AAF to authenticate the user
2) AFF sends its callback to the API
3) API redirects back to the web UI using temporary auth token (that'll expire in 30 seconds)
4) use temporary auth token or to get user details and invalidate it
5) respond back equivalent of `POST /auth` (username/password request)

Redirect users back to front end after validating JWT

---

app/api/group_sets.rb
app/models/group.rb
app/models/unit.rb
app/serializers/group_serializer.rb
db/migrate/20170116035300_add_group_number.rb
db/schema.rb
test_files/COS10001-TestImportGroups.csv
test_files/group_upload.csv

Adds a `group_number` concept so that a group may have a name and a consistent number.
Also fixes a number of issues:
- remove group member if not part of group fixed
- prevent switching a group's tutorial if the group set does not allow groups to be part of multiple tutorials
- ensures students from the _right_ tutorial can only be added to a tutorial (given non-mixed tutorial groupset)
- prevent member from being added to group twice

Fix issues with groups and assign number to groups for reference

---

app/api/authentication.rb
app/models/role.rb

This PR will set a new user's account type to a tutor if AAF returns that they are a staff

QUALITY: Set user role to staff if aaf returns staff

---

lib/helpers/database_populator.rb
lib/helpers/find_or_create_students.rb

This PR will ensure that the database populator is successful when AAF is enabled by not assigning a password to the password field on a User (which does not exist if AAF is enabled)

FIX: Only use password field in User if AAF is not enabled

---

app/api/submission/portfolio_api.rb
app/api/submission/portfolio_evidence_api.rb

This PR fixes issues in https://github.com/doubtfire-lms/doubtfire-web/pull/81.
The native `object` in Chrome and Firefox must receive a MIME type `application/pdf` **without** the `Content-Disposition` header set as `attachment`. Safari seems to ignore this, which is why it was rendering in Safari.

Add optional argument to download PDF as attachment

---

app/models/task.rb

Previously DF copied files across into "new" one by one. This occasionally caused concurrency issues where the back end PDF creation accessed these files before they were all copied across. This caused the creation of the PDF to fail. Moving the folder should address this issue.

FIX: Change copy of files to move dir

---

.gitmodules

Since the DSTIL repository went private, the Travis builds were failing.

Remove git submodules

---

app/models/task.rb
test/api/units/task_definitions_test.rb

Ensure that the **new** folder is created on submission of files if it does not already exist.

TEST: Add tests to check that the new folder is created

---

.editorconfig
app/api/api.rb
app/api/task_definitions.rb
app/models/task.rb
test/api/groups_test.rb

Posting a comment to a group task previously failed, due to inability to ensure group submission. This PR fixes this issue by testing for group presence on comment posting. Side effect will be that these comments are invisible to group prior to the first submission of this task.

FIX: Correct posting of comments to group tasks without groups

---

app/helpers/file_helper.rb
app/models/task_comment.rb
test/api/comments/comment_test.rb
test/api/groups_test.rb

Ensure that comments for group tasks are able to resolve paths to attachments. For group tasks, attachments are associated with the student in the file system rather than the group (allowing comments to be added before groups are formed).
Pull request also ensures that comment attachments are deleted when comment is destroyed.

FIX: Enable comment attachments for group tasks

---

Gemfile
Gemfile.lock
test/test_helper.rb

'minitest-osx' gem has been removed from RubyGems.
https://rubygems.org/gems/minitest-osx
> This gem previously existed, but has been removed by its owner.
Console output:
```
Step 16/19 : RUN bundle install --without production replica
---> Running in 651952df1e09
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/.............
Could not find minitest-osx-0.1.0 in any of the sources
ERROR: Service 'api' failed to build: The command '/bin/sh -c bundle install --without production replica' returned a non-zero code: 7
```

Remove an unavailable gem minitest-osx

---

app/models/unit.rb

Allow admin staff to assist unit chairs with the unit setup processes without needing to enrol themselves within the unit as a unit chair.

ENHANCE: Expand admin role to assist with unit administration

---

app/models/user.rb

Names that were blank but entered as "-" failed to import.

FIX: Correct issue with titleize stripping blank names

---

.travis.yml
Dockerfile
docker-compose.yml

This PR will:
- make docker-compose working again
- install ffmpeg to support audio recording feature

Docker-compose

---

app/views/portfolio/portfolio_pdf.pdf.erb

Non-printable characters in the portfolio cause the creation of the portfolio to fail. This PR corrects this to ensure the portfolio creation works and these characters are stripped out of comments.

FIX: Remove non-printable characters from comments in portfolio

---

app/api/submission/batch_task.rb
app/controllers/lecture_resource_downloads_controller.rb
app/controllers/portfolio_downloads_controller.rb
app/controllers/task_downloads_controller.rb
app/controllers/task_submission_pdfs_controller.rb
app/helpers/file_helper.rb
app/models/unit.rb
lib/tasks/maintenance.rake

This PR moves the creation of temporary files to within the student work folder - away from /tmp
A rake maintenance task is added to clean up files within the new tmp folder.

FIX: Move tmp files out of tmp

---

app/models/teaching_period.rb
test/models/teaching_period_test.rb

This PR fixes an issue where updating the dates for a teaching period cause the units to become invalid.

FIX: Correct issue with teaching period date changes not propagating to units

---

app/models/task.rb

(diff.to_i / 7).ceil was returning 0 if the number of days extension required was less than 7, as the diff was being converted to an int and then ceil'd. So for example a 1 day extension was erroring as it was not allowed any extension.
to_f now applies the ceil correctly, so the above scenario will return the 1 week extension application

FIX: .ceil of an integer not returning what was expected

---

docker-compose.yml

Set DF_DOCKER_MACHINE_IP variable to `api` by default.

FIX: docker-compose.yml

---

app/models/task.rb

Tested on localhost with an 8MB PDF, and ran PDF generation task to test.

ENHANCE: Increase submission file size limit from 5MB to 10MB

---

test/api/comments/comment_test.rb
test/api/csv_test.rb
test/api/groups_test.rb
test/api/units/task_definitions_test.rb
test/helpers/test_file_helper.rb
test/models/file_helper_test.rb

Add two helpers which allow to get the full path of csv files and other file types and make sure all test file paths are from root

TEST: Add a helper to get full test file paths

---

setup.sh

Please refer to the commit https://github.com/doubtfire-lms/doubtfire-api/commit/9dec0bf6d1c770f625a174c4ac1ba50db7ae1ee8 which changes `setup.sh` to restart Postgres after installation on Linux, preventing a database connectivity issue during the user & database creation that follows.
Re-installed `doubtfire-api` on a fresh installation of WSL's Ubuntu distribution via `setup.sh`—we didn't run into the database connectivity error.

FIX: Restart postgres after Linux installation via setup script

---

Gemfile
Gemfile.lock
app/api/api.rb
app/api/webcal_api.rb
app/models/user.rb
app/models/webcal.rb
app/models/webcal_unit_exclusion.rb
app/serializers/webcal_serializer.rb
db/migrate/20200817020024_create_webcals.rb
db/migrate/20200908115109_create_webcal_unit_exclusions.rb
db/migrate/20200909074930_add_reminders_to_webcal.rb
db/schema.rb
test/api/webcal_api_test.rb
test/models/webcal_test.rb

Adds functionality that serves key task dates of units that a user is enrolled in, as an iCalendar, importable into Outlook/Google calendars.
The corresponding frontend PR is: https://github.com/doubtfire-lms/doubtfire-web/pull/293
Unit tests ensure that webcals,
- Include only task definitions of current units
- Include only task definitions that are targeted
- Include only task definitions of units that aren't excluded
- Include events with target dates of all task definitions
- Include events for start & end dates if include_start_dates
- Include events with extended date if available
...and that, of the API,
- Setting enabled creates or destroys webcal
- Enables with sensible defaults
- should_change_guid parameter changes the Webcal guid
- Ical endpoint is public and serves webcal …

NEW: Allow exporting task dates in iCalendar format

---

app/api/tasks_api.rb
app/api/units_api.rb
app/models/task_pin.rb
app/models/unit.rb
db/migrate/20200512143828_create_task_pins.rb
db/schema.rb
test/api/tasks_test.rb
test/factories/task_pins.rb
test/models/task_pin_test.rb

This branch continues @Justfeedme's work in making tasks pinnable #280.
Introduces 2 new endpoints,
https://github.com/doubtfire-lms/doubtfire-api/pull/292/commits/dca86d57791f94c58f08ba7be6390c183cb986fd includes the following tests,
1. Tasks are un/pinnable by tutors & convenors, and not by students & admins.
2. Tutors & convenors only pin tasks of units to which they are assigned.
3. The list of tasks returned for the task inbox includes their un/pinned states.

NEW: Pinnable tasks

---

app/api/units_api.rb

A bug existed where when using `.key?` when detecting if a draft task definition id was passed into the parameters would also equate to `true` when the front-end returned null or an empty string.
The tests previously created in `units_api_tests.rb` have no failures.

FIX: Fix updating unit on units API when draft learning summary id is null or empty

---

Gemfile
Gemfile.lock

Latest updates on the deployment server use a version of image magic that is not compatible with the existing version. This PR updates the rmagick version and has tested that this update does not cause issues.
- Bug fix (non-breaking change which fixes an issue)
When deployed the bundle will need to be reinstalled

Upgrade rmagick to work with latest image magic deployment

---

app/models/task.rb

This PR fixes a bug in which new files uploaded via the "Update files" (rather than a new submission) wouldn't override unprocessed new files.
For example:
Submission fileset#1 -> Update Files with fileset#2 -> PDF Generated would generate with fileset#1.
The issue was caused by FileUtils.mv not operating as expected.
In fact, the underlying unix mv command generated by the FileUtils method *does* work as expected, which seems to indicate to me a bug in FileUtils. This solution is a workaround while still retaining the benefits of using mv (files are still renamed not copied).
Existing unit tests run successfully, although new unit tests to test for this bug should be written I am authoring the PR now as this *may* be a critical bug worth deploying ASAP.

FIX: Ensure new files override unprocessed files

---

app/models/project.rb
app/models/unit.rb

This fixes an issue where students could disappear from Doubtfire if they only had tasks for task definitions higher than their target grade.

FIX: Correct student list query to ensure all students appear

---

app/models/webcal.rb
db/schema.rb
test/api/webcal_api_test.rb
test/models/webcal_test.rb

Issue described at, and fixes #316

Correctly assign webcal reminder descriptions. Fixes #316

---

app/api/webcal_api.rb
test/api/webcal_api_test.rb

This removes the user id `7` that was mistakenly hardcoded in the webcal API unit exclusion logic in cc13c5630e5f486c75b61b385ed1f2cc7392f40f.
Not sure how I missed this ...just 😐😶🤦.
https://github.com/doubtfire-lms/doubtfire-api/blob/d7e66aa353dd88da98d51c30732ad4ad674090da/test/api/webcal_api_test.rb#L112-L133
👆 which hits 👇<br>
https://github.com/doubtfire-lms/doubtfire-api/blob/1037242d44a1dfaeda0db80b42a4ae1da4b69579/app/api/webcal_api.rb#L104-L116
Installing `texlive-full` now; will update with a screenshot.

FIX: Remove hardcoded user ID in webcal unit exclusion logic

---

Dockerfile
docker-entrypoint.sh

When we restart the doubtfire-api container, we need to delete the ` server.pid ` file in ` /tmp/pids ` manually. So I added a docker entrypoint srcipt to delete that file everytime before the container start if  ` server.pid ` exist. 
I build the docker image in my local dev environment, then develop the project with that image. To test it, I firstly went to the container bash, make sure the ` server.pid ` file is in the right path then I restart the container several times and restart my PC to test if we still need to delete ` server.pid ` file manually. Also by monitoring the pids folder I can clearly see the file was removed then created when restart the container.

fix:fix the manual delete servers.pid file after restart container

---

app/api/entities/project_entity.rb

refactor ternary operator which creates student_name to ensure nicknames with a value of "" are not rendered
Replaced the .nil? check with .blank? to ensure a nickname with an empty string won't be added to project_entity::student_name.
Fixes #363

Fix: stop empty nicknames from rendering in student_name

---

.ci-setup/texlive-install.sh
Dockerfile

Updates the Ruby base image to support multi-arch image builds.
* Bullseye base image has glibc >= 2.9 to support nokigiri native gem.
* texlive install uses dir path from uname to always have correct path.
Note: I built the images with:  `docker buildx build --platform linux/amd64,linux/arm64 . -t jake/doubtfire-api-test`

build: multi-platform Dockerfile and tex

---

.gitignore

Trivial change to ignore locally installed gems. Path specified is the default in bundle's help messages. This avoids having tens of thousands of untracked files if I use bundle to install the gems outside of a docker container.
Trivial config update.
`git` now ignores locally installed gems as intended.

fix: ignore locally installed gems

---

.github/workflows/push.yml

This fixes our long-broken CI and we can run automated unit tests with GitHub Actions again. The service is called `mariadb` now instead of `mysql`, so previously no tests are ran because the db wasn't even started.
Refer to this run:
https://github.com/ublefo/doubtfire-api/runs/7600928237?check_suite_focus=true

ci: update service name to fix ci

---

.github/workflows/push.yml

- Update some descriptions to make things easier to understand
- Migrate to use a mariadb service container to avoid having to install it in the app container
- Add heathchecks to ensure db is ready before anything else happens
Minor improvements and restructuring.
Refer to this run:
https://github.com/ublefo/doubtfire-api/runs/7603679827?check_suite_focus=true

ci: improve descriptions and switch to mariadb service container

---

.ci-setup/texlive-install.sh

Overall changes:
- quote variables that should be quoted to increase robustness
- switch to `$(command)` instead of `` `command` `` as suggested by shellcheck
- improve readability of output messages by adding some separators
Area-specific changes:
- use `set -e` to make sure any failed command will produce a failure
- refactor `APP_PATH` logic
- add `TEX_COMPILER` for testing the specific tex compiler we are using
- switch to HTTPS instead of relying on protocol upgrade redirects
- add final checks to test `TEX_COMPILER`'s existence and compile a test  document
Minor enhancement to improve reliability.
https://github.com/ublefo/doubtfire-api/runs/7617634785?check_suite_focus=true

enhance: refactor texlive installation script

---

.github/workflows/push.yml

Some minor refactoring for the workflow manifest to improve robustness, and prepare for the upcoming additional jobs that run on arm64 that I plan to implement.
- Refactor the terrifyingly long line of environment variables and ensure we have a single source of truth
- Split db populate and unit test task into separate steps
https://github.com/ublefo/doubtfire-api/runs/7620273639?check_suite_focus=true

chore: refactor workflow manifest and split steps

---

.ci-setup/newpax.lua.patch
.ci-setup/texlive-install.sh
app/helpers/file_helper.rb
app/views/layouts/application.pdf.erbtex
app/views/portfolio/portfolio_pdf.pdf.erb
app/views/task/task_pdf.pdf.erb

This fix will only preserve **links** (hyperlinks and internal links) and nothing else. This is a limitation of the TeX packages we have available, both `pax` and `newpax` can only extract links and nothing else. The TeX engine _can_ insert annotations with a package like `pdfcomment`, but we cannot extract them from the PDFs we are including, so this is as good as it gets right now.
- Global preamble `app/views/layouts/application.pdf.erbtex`
- Task submission PDF template `app/views/task/task_pdf.pdf.erb`
- Portfolio PDF template `app/views/portfolio/portfolio_pdf.pdf.erb`
Fixes:  https://github.com/doubtfire-lms/doubtfire-api/issues/130 and https://github.com/doubtfire-lms/doubtfire-web/issues/337
Does **not** fix: https://github.com/doubtfire-lms/doubtfire-api/issues/326
CI run: …

fix: preserve links in PDF

---

config/environments/development.rb
config/environments/production.rb
lib/tasks/generate_pdfs.rake

Introduce a new config in the environment so we can set logging verbosity for the `generate_pdfs` task to `:warn`. This way successful PDF generation runs should not generate any new logs in production.
Fixes #367

enhance: reduce logging verbosity for generate_pdfs in production

---

app/views/notifications_mailer/weekly_student_summary.html.erb

Correct the bad tag in email template for the "due soon" list. 
Minor template change to fix a cosmetic issue.
Fixes #137

fix: correct the bad tag in email template for the "due soon" ul

---

CONTRIBUTING.md
README.md

Remove the reliance on a random 3rd party site for project logo. If you load this file in an editor that previews markdown, it sends out an unencrypted HTTP request and relies on a redirect for protocol upgrade which could potentially be insecure. We could change it to HTTPS, but it's better to just use our current logo in the repo instead.
There are no code changes.

chore: stop relying on a third party site for logo

---

Dockerfile
app/helpers/file_helper.rb
app/models/task.rb
deployAppSvr.Dockerfile

Turnitin's originality report PDFs all seem to have broken xref tables, and this makes it impossible for students to submit originality reports from Turnitin. The tex compiler really doesn't like PDFs with broken xref tables and will fail if you use `\includepdf` on such a file. Most PDF readers will silently ignore or repair this on the fly so it's hard to detect unless you know what to look for. `exiftool` is a tool that can catch this. Some fields in the following output have been redacted for privacy reasons.
```
$ exiftool turnitin-report.pdf 
======== turnitin-report.pdf
ExifTool Version Number         : 12.42
File Name                       : turnitin-report.pdf
Directory                       : .
File Size                       : 1000 kB
File Modification Date/Time     : 
File …
```

Perform automatic PDF repair with qpdf on task submissions

---

.github/workflows/codeql.yml
.github/workflows/push.yml
.github/workflows/rubocop.yml
README.md

- Enable the CodeQL vulnerability scanner service https://codeql.github.com/
- Enable RuboCop linting
RuboCop workflow taken from: https://github.com/rails/rails/blob/main/.github/workflows/rubocop.yml

ci: add codeql and rubocop workflows

---

.rubocop_todo.yml

Raise the limit again so we don't keep tripping this cop. We can deal with refactoring later down the line after we work out most of the todo items.

chore: raise line limit in todo to silence the warning for now

---

.ci-setup/newpax.lua.patch

Students have been reporting higher error rates after newpax has been introduced due to the fact that it can't cope with nonexistent creation date in the PDF metadata. Fix this by hard-coding the date for now as an emergency fix, and we will look into addressing this properly later on.

fix: hard-code date in newpax to avoid nil dates

---

app/models/project.rb

This pull request fixes an urgent issue resulting in large portfolio file sizes.
Use of new pax is resulting in portfolios that are 10x their normal size. Compressing after creation fixes this until the issue with the use of new pax can be resolved.

fix: ensure portfolio PDFs are compressed

---

CHANGELOG.md
app/views/portfolio_evidence_mailer/portfolio_failed.html.erb
app/views/portfolio_evidence_mailer/portfolio_ready.html.erb
test/mailers/unit_mail_test.rb

Current portfolio generation emails do not link to the portfolio creation page. This PR corrects the links to ensure they will go to the portfolio creation page if the user is logged in.
Also fixes the links in the change log that incorrectly refer to the deploy project within which the API is a sub-project.

Correct links in portfolio generation emails

---

app/api/entities/project_entity.rb
test/api/auth_test.rb
test/api/groups_api_test.rb
test/api/projects_api_test.rb
test/api/students_api_test.rb
test/api/unit_roles_test.rb
test/api/units/task_definitions_api_test.rb
test/api/units_api_test.rb
test/models/unit_model_test.rb

This PR addresses all failing tests in the new entity service version of the API. Unit tests should now function as expected.

refactor: ensure all unit tests function in new back end services

---

app/models/webcal.rb

If a student withdraws from a unit, tasks will still show up in the webcal feed, because we did not delete the project. This fixes the oversight and excludes tasks from withdrawn units.

fix: exclude tasks from withdrawn units in webcal feed

---

Dockerfile
app/api/admin/overseer_admin_api.rb
app/api/entities/overseer_image_entity.rb
app/models/overseer_image.rb
config/application.rb
db/migrate/20230206021556_add_columns_to_overseer_images.rb
db/schema.rb
test/models/overseer_image_test.rb

Added the ability to pull a Docker image. To be used for pulling Overseer images from the front end. This new feature has required the installation of Docker in the doubtfire-api container, which is included in this commit.
This was tested through the test file 'overseer_image_test' where the validity of a tag is checked for accuracy, including testing if the tag can be injected with code.

feat: pull overseer docker image
